author:
  avatar: /assets/images/logo.png
  bio: hyeon's Tech News
  location: Seoul, Korea
  name: hyeon
  url: https://jhyun3464.github.io
defaults:
- scope:
    path: ''
    type: posts
  values:
    author_profile: true
    comments: false
    layout: single
    read_time: true
    related: true
    share: false
description: jhinux 의 정리글
github_username: null
locale: ko-KR
logo: /assets/images/logo.png
minimal_mistakes_skin: dark
paginate: 5
future: true
plugins:
- jekyll-remote-theme
- jekyll-paginate
- jekyll-include-cache
- jekyll-seo-tag
- jekyll-feed
- jekyll-sitemap
remote_theme: mmistakes/minimal-mistakes
repository: null
title: hyeon's Tech News
url: 'https://jhyun3464.github.io'
