author:
  avatar: /assets/images/logo.png
  bio: Hacker News Ops Center
  location: Seoul, Korea
  name: jhinux
  url: https://jhinux.tistory.com/
defaults:
- scope:
    path: ''
    type: posts
  values:
    author_profile: true
    comments: false
    layout: single
    read_time: true
    related: true
    share: false
description: Hacker News & Tech Trends
github_username: null
locale: ko-KR
logo: /assets/images/logo.png
minimal_mistakes_skin: dark
paginate: 5
plugins:
- jekyll-remote-theme
- jekyll-paginate
- jekyll-include-cache
- jekyll-seo-tag
- jekyll-feed
- jekyll-sitemap
remote_theme: mmistakes/minimal-mistakes
repository: null
title: jhinux's github pages
url: ''
